services:
  # Database for Users Service
  users-db:
    image: postgres:alpine
    container_name: users-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library_users_db
    # volumes:
    #   - users-db-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - library-network
    ports:
      - "5430:5432"

  # Database for Books Service
  books-db:
    image: postgres:alpine
    container_name: books-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library_books_db
    # volumes:
    #   - books-db-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - library-network
    ports:
      - "5431:5432"

networks:
  library-network:
    driver: bridge
# volumes:
#   books-db-data:
#   users-db-data:
