services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SERVICE=api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - users-service
    networks:
      - library-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SERVICE=auth-service
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    networks:
      - library-network

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-service
    environment:
      - SERVICE=users-service
      - DATABASE_URL="postgres://root:secret@users-db:5432/library_users_db"
    ports:
      - "8082:8082"
    depends_on:
      - users-db
    networks:
      - library-network

  # Database for Users Service
  users-db:
    image: postgres:alpine
    container_name: users-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library_users_db
    volumes:
      - users-db-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - library-network
    ports:
      - "5430:5432"

  # Database for Books Service
  books-db:
    image: postgres:alpine
    container_name: books-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library_books_db
    volumes:
      - books-db-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - library-network
    ports:
      - "5431:5432"

  # Database for Auth Service
  auth-db:
    image: postgres:alpine
    container_name: auth-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: library_auth_db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - library-network
    ports:
      - "5432:5432"

networks:
  library-network:
    driver: bridge

volumes:
  books-db-data:
  users-db-data:
  auth-db-data:
